[package]
name = "ohttp-server"
version = "0.5.3"
authors = ["Martin Thomson <mt@lowentropy.net>"]
edition = "2021"

[features]
default = ["rust-hpke"]
nss = ["ohttp/nss"]
rust-hpke = ["ohttp/rust-hpke"]

[dependencies]
env_logger = {version = "0.10", default-features = false}
hex = "0.4"
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
warp = { version = "0.3", features = ["tls"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "stream"] }
futures-util = "0.3.30"
futures = "0.3.30"

[dependencies.bhttp]
path= "../bhttp"
features = ["bhttp", "write-http"]

[dependencies.ohttp]
path= "../ohttp"
features = ["server"]
default-features = false
